// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhDTD4t_7mxqtJeKPm9iyYhzsHXWyXhEA',
    appId: '1:819562866779:web:db17729b791d8ae7c3377e',
    messagingSenderId: '819562866779',
    projectId: 'best-candidate',
    authDomain: 'best-candidate.firebaseapp.com',
    storageBucket: 'best-candidate.appspot.com',
    measurementId: 'G-QGXSTC59CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaNlFlKN8w3nnh7I3ZTWN9QWjO7LgoofY',
    appId: '1:819562866779:android:23e4fdecc447b5b4c3377e',
    messagingSenderId: '819562866779',
    projectId: 'best-candidate',
    storageBucket: 'best-candidate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAriLxmY7xST_8Cuv-j7EI4HMeYIyGG7Q4',
    appId: '1:819562866779:ios:c7c94efb2ebcf9eec3377e',
    messagingSenderId: '819562866779',
    projectId: 'best-candidate',
    storageBucket: 'best-candidate.appspot.com',
    iosBundleId: 'com.example.bestCandidate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAriLxmY7xST_8Cuv-j7EI4HMeYIyGG7Q4',
    appId: '1:819562866779:ios:c7c94efb2ebcf9eec3377e',
    messagingSenderId: '819562866779',
    projectId: 'best-candidate',
    storageBucket: 'best-candidate.appspot.com',
    iosBundleId: 'com.example.bestCandidate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhDTD4t_7mxqtJeKPm9iyYhzsHXWyXhEA',
    appId: '1:819562866779:web:0bbc1dae4751ab98c3377e',
    messagingSenderId: '819562866779',
    projectId: 'best-candidate',
    authDomain: 'best-candidate.firebaseapp.com',
    storageBucket: 'best-candidate.appspot.com',
    measurementId: 'G-CVDHCZ7K11',
  );
}
